# Generated by Django 5.0.4 on 2024-04-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225)),
                ('email', models.EmailField(blank=True, max_length=225, unique=True)),
                ('subject', models.CharField(blank=True, max_length=225)),
                ('message', models.TextField(blank=True, max_length=225)),
                ('sent_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
